<?xml version="1.0" encoding="utf-8"?><Database Name="user" Class="DataClassesRoomDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=user;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="userConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Room" Member="Room">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.his_tblData1" Member="his_tblData1">
    <Type Name="his_tblData1">
      <Column Name="RecordID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="DataID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BATCH_INFO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="IMAGE_FILE_NAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AGENT_COMPANY_NAME" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="AGENT_FAX" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AGENT_PERSON_NAME" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AGENT_PHONE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AGENT_STATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AGENT_ZIP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CANCEL_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CANCEL_PREMIUM_DUE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CANCEL_PREMIUM_DUE_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CANCEL_REASON" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CARRIER_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CHANGE_EFFECTIVE_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="COINSURANCE_PERCENT" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="CONTINUOUS_TO_CANCEL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="DOCUMENT_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DOCUMENT_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EFFECTIVE_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EXPIRE_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="INSURANCE_AMOUNT" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="INSURANCE_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INSURED_LOCATION_NUMBER" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="INSURED_LOCATION_OR_VEH_NUMBER" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="INSURED_MAIL_ADDRESS1" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="INSURED_MAIL_ADDRESS2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="INSURED_MAIL_CITY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="INSURED_MAIL_STATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURED_MAIL_ZIP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="INSURED_NAME" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="LOAN_NUMBER" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="LOSS_PAYEE_ADDRESS1" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="LOSS_PAYEE_ADDRESS2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="LOSS_PAYEE_CITY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LOSS_PAYEE_NAME" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="LOSS_PAYEE_STATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LOSS_PAYEE_ZIP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="POLICY_NUMBER" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="PREMIUM_AMOUNT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NUMOFUNITS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="REALESTATE_ADDRESS1" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="REALESTATE_ADDRESS2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="REALESTATE_CITY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="REALESTATE_STATE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="REALESTATE_ZIP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="REINSTATE_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="REINSTATE_WITHOUT_LAPSE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TERM" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="WHO_PAYS_PREMIUM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="WINDHAILDED" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="AGENT_ADDRESS" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="AGENT_CITY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DOCUMENT_SIGNED" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RANGE_ADDRESS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="POLICY_10DAYNONPAYNOTICE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_30DAYCANCELNOTICE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_CONTTOCANC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_CUTTHROUGHENDORSE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_DISCLOSUREFORMREC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_INSPAYSPREMIUM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_MOLDINCLUDE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_RISKPURCHASINGGROUP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_TENANTPROVIDED" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POLICY_TERRORINCLUDE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NOTES" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ADDTNL_INSURED_NAME" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="ADDTNL_INSURED_ADDRESS1" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="ADDTNL_INSURED_CITY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ADDTNL_INSURED_STATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ADDTNL_INSURED_ZIP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DEL_INTEREST_AI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="HAZARD_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="HAZARD_WINDHAILDED" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="HAZARD_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="HAZARD_ACV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_AGREEDAMNTVAL" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_ALLRISK" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_BLANKETPOLLIMIT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_MULTILAYER" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_RC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_WAIVEROFSUBJ" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HAZARD_WINDEXCLUDED" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LIABILITY_LIABILITY1" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="LIABILITY_LIABILITY2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="LIABILITY_LIABILITY3" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="LIABILITY_DLGENADDLIM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_AMOUNT" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_EXTRAEXPENSE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_6MOINDEMNITY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_12MOINDEMNITY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_18MOINDEMNITY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_24MOINDEMNITY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUSNSINCOME_ACTUALLOSSSUST" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUILDINGORD_PROPUNDMG" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BUILDINGORD_DEMOCOST" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BUILDINGORD_INCRCOST" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BUILDINGORD_DEMOLITION" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BUILDINGORD_INCREASECONSTRCOST" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BOILERMACH_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BOILERMACH_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="BOILERMACH_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="TERRORISM_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="TERRORISM_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="TERRORISM_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="EARTHQUAKE_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="EARTHQUAKE_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="EARTHQUAKE_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WIND_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WIND_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WIND_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="FLOOD_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="FLOOD_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="FLOOD_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WORKERSCOMP_WORKERS1" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WORKERSCOMP_WORKERS2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WORKERSCOMP_WORKERS3" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="WORKERSCOMP_STATLIMIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EXCESS_LIABILITY1" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="EXCESS_LIABILITY2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="EXCESS_LIABILITY3" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="EXCESS_MULTILAYER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SINKHOLE_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="SINKHOLE_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="SINKHOLE_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="PROFLIAB_LIABILITY1" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="PROFLIAB_LIABILITY2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="PROFLIAB_LIABILITY3" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="POLLUTION_LIABILITY1" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="POLLUTION_LIABILITY2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="POLLUTION_LIABILITY3" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="CONTENTS_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="CONTENTS_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="CONTENTS_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_BOILERMACH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_BUILDINGORD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_BUSNSINCOME" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_CONTENTS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_EARTHQUAKE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_EXCESS" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_FLOOD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_HAZARD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_LIABILITY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_TERRORISM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_WIND" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="INSURANCE_ID_WORKERSCOMP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PAYEE_NAME" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="PAYEE_ADDRESS1" Type="System.String" DbType="VarChar(225)" CanBeNull="true" />
      <Column Name="PAYEE_CITY" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PAYEE_STATE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PAYEE_ZIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AMOUNT_DUE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="PAYMENT_DUE_OR_CHECK_DATE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="POLICY_TYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntryFlag" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="WorkID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="InserTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REPLACEMENTVALUE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="REPLACEMENTCOST" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="FLOODREPLACEMENTVALUE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FLOODREPLACEMENTCOST" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NFIP_FLOOD_ZONE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UNITOWNER" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LIEN_HOLDER_NAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="LIEN_HOLDER_ADDRESS1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LIEN_HOLDER_CITY" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="LIEN_HOLDER_STATE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LIEN_HOLDER_ZIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEL_INTEREST_LH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OTHER_COLL_SERIAL_NUMBER" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OTHER_COLL_YEAR" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="OTHER_COLL_MAKE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OTHER_COLL_MODEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OTHER_COLL_ZIP" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FLDCONTENTS_PROPERTY" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="FLDCONTENTS_DEDUCTIBLE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="FLDCONTENTS_COINSURANCE" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="FLDCONTENTSREPLACEMENTVALUE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FLDCONTENTSREPLACEMENTCOST" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NFIP_FLDCONTENTS_ZONE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="STIC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>