#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="user")]
	public partial class DataClassesRoomDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    #endregion
		
		public DataClassesRoomDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["userConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesRoomDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesRoomDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesRoomDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesRoomDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Room> Room
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<his_tblData1> his_tblData1
		{
			get
			{
				return this.GetTable<his_tblData1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Number;
		
		private string _Price;
		
		private string _Class;
		
		private string _Status;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnPriceChanging(string value);
    partial void OnPriceChanged();
    partial void OnClassChanging(string value);
    partial void OnClassChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Room()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NChar(20)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="NChar(10)")]
		public string Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="NChar(10)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.his_tblData1")]
	public partial class his_tblData1
	{
		
		private decimal _RecordID;
		
		private string _DataID;
		
		private string _BATCH_INFO;
		
		private string _IMAGE_FILE_NAME;
		
		private string _AGENT_COMPANY_NAME;
		
		private string _AGENT_FAX;
		
		private string _AGENT_PERSON_NAME;
		
		private string _AGENT_PHONE;
		
		private string _AGENT_STATE;
		
		private string _AGENT_ZIP;
		
		private string _CANCEL_DATE;
		
		private System.Nullable<decimal> _CANCEL_PREMIUM_DUE;
		
		private string _CANCEL_PREMIUM_DUE_DATE;
		
		private string _CANCEL_REASON;
		
		private string _CARRIER_NAME;
		
		private string _CHANGE_EFFECTIVE_DATE;
		
		private System.Nullable<decimal> _COINSURANCE_PERCENT;
		
		private string _CONTINUOUS_TO_CANCEL;
		
		private System.Nullable<decimal> _DEDUCTIBLE;
		
		private string _DOCUMENT_DATE;
		
		private string _DOCUMENT_ID;
		
		private string _EFFECTIVE_DATE;
		
		private string _EXPIRE_DATE;
		
		private System.Nullable<decimal> _INSURANCE_AMOUNT;
		
		private string _INSURANCE_ID;
		
		private string _INSURED_LOCATION_NUMBER;
		
		private string _INSURED_LOCATION_OR_VEH_NUMBER;
		
		private string _INSURED_MAIL_ADDRESS1;
		
		private string _INSURED_MAIL_ADDRESS2;
		
		private string _INSURED_MAIL_CITY;
		
		private string _INSURED_MAIL_STATE;
		
		private string _INSURED_MAIL_ZIP;
		
		private string _INSURED_NAME;
		
		private string _LOAN_NUMBER;
		
		private string _LOSS_PAYEE_ADDRESS1;
		
		private string _LOSS_PAYEE_ADDRESS2;
		
		private string _LOSS_PAYEE_CITY;
		
		private string _LOSS_PAYEE_NAME;
		
		private string _LOSS_PAYEE_STATE;
		
		private string _LOSS_PAYEE_ZIP;
		
		private string _POLICY_NUMBER;
		
		private System.Nullable<decimal> _PREMIUM_AMOUNT;
		
		private System.Nullable<decimal> _NUMOFUNITS;
		
		private string _REALESTATE_ADDRESS1;
		
		private string _REALESTATE_ADDRESS2;
		
		private string _REALESTATE_CITY;
		
		private string _REALESTATE_STATE;
		
		private string _REALESTATE_ZIP;
		
		private string _REINSTATE_DATE;
		
		private string _REINSTATE_WITHOUT_LAPSE;
		
		private System.Nullable<decimal> _TERM;
		
		private string _WHO_PAYS_PREMIUM;
		
		private System.Nullable<decimal> _WINDHAILDED;
		
		private string _AGENT_ADDRESS;
		
		private string _AGENT_CITY;
		
		private string _DOCUMENT_SIGNED;
		
		private string _RANGE_ADDRESS;
		
		private string _POLICY_10DAYNONPAYNOTICE;
		
		private string _POLICY_30DAYCANCELNOTICE;
		
		private string _POLICY_CONTTOCANC;
		
		private string _POLICY_CUTTHROUGHENDORSE;
		
		private string _POLICY_DISCLOSUREFORMREC;
		
		private string _POLICY_INSPAYSPREMIUM;
		
		private string _POLICY_MOLDINCLUDE;
		
		private string _POLICY_RISKPURCHASINGGROUP;
		
		private string _POLICY_TENANTPROVIDED;
		
		private string _POLICY_TERRORINCLUDE;
		
		private string _NOTES;
		
		private string _ADDTNL_INSURED_NAME;
		
		private string _ADDTNL_INSURED_ADDRESS1;
		
		private string _ADDTNL_INSURED_CITY;
		
		private string _ADDTNL_INSURED_STATE;
		
		private string _ADDTNL_INSURED_ZIP;
		
		private string _DEL_INTEREST_AI;
		
		private System.Nullable<decimal> _HAZARD_PROPERTY;
		
		private System.Nullable<decimal> _HAZARD_DEDUCTIBLE;
		
		private System.Nullable<decimal> _HAZARD_WINDHAILDED;
		
		private System.Nullable<decimal> _HAZARD_COINSURANCE;
		
		private string _HAZARD_ACV;
		
		private string _HAZARD_AGREEDAMNTVAL;
		
		private string _HAZARD_ALLRISK;
		
		private string _HAZARD_BLANKETPOLLIMIT;
		
		private string _HAZARD_MULTILAYER;
		
		private string _HAZARD_RC;
		
		private string _HAZARD_WAIVEROFSUBJ;
		
		private string _HAZARD_WINDEXCLUDED;
		
		private System.Nullable<decimal> _LIABILITY_LIABILITY1;
		
		private System.Nullable<decimal> _LIABILITY_LIABILITY2;
		
		private System.Nullable<decimal> _LIABILITY_LIABILITY3;
		
		private string _LIABILITY_DLGENADDLIM;
		
		private System.Nullable<decimal> _BUSNSINCOME_AMOUNT;
		
		private System.Nullable<decimal> _BUSNSINCOME_EXTRAEXPENSE;
		
		private System.Nullable<decimal> _BUSNSINCOME_COINSURANCE;
		
		private string _BUSNSINCOME_6MOINDEMNITY;
		
		private string _BUSNSINCOME_12MOINDEMNITY;
		
		private string _BUSNSINCOME_18MOINDEMNITY;
		
		private string _BUSNSINCOME_24MOINDEMNITY;
		
		private string _BUSNSINCOME_ACTUALLOSSSUST;
		
		private System.Nullable<decimal> _BUILDINGORD_PROPUNDMG;
		
		private System.Nullable<decimal> _BUILDINGORD_DEMOCOST;
		
		private System.Nullable<decimal> _BUILDINGORD_INCRCOST;
		
		private string _BUILDINGORD_DEMOLITION;
		
		private string _BUILDINGORD_INCREASECONSTRCOST;
		
		private System.Nullable<decimal> _BOILERMACH_PROPERTY;
		
		private System.Nullable<decimal> _BOILERMACH_DEDUCTIBLE;
		
		private System.Nullable<decimal> _BOILERMACH_COINSURANCE;
		
		private System.Nullable<decimal> _TERRORISM_PROPERTY;
		
		private System.Nullable<decimal> _TERRORISM_DEDUCTIBLE;
		
		private System.Nullable<decimal> _TERRORISM_COINSURANCE;
		
		private System.Nullable<decimal> _EARTHQUAKE_PROPERTY;
		
		private System.Nullable<decimal> _EARTHQUAKE_DEDUCTIBLE;
		
		private System.Nullable<decimal> _EARTHQUAKE_COINSURANCE;
		
		private System.Nullable<decimal> _WIND_PROPERTY;
		
		private System.Nullable<decimal> _WIND_DEDUCTIBLE;
		
		private System.Nullable<decimal> _WIND_COINSURANCE;
		
		private System.Nullable<decimal> _FLOOD_PROPERTY;
		
		private System.Nullable<decimal> _FLOOD_DEDUCTIBLE;
		
		private System.Nullable<decimal> _FLOOD_COINSURANCE;
		
		private System.Nullable<decimal> _WORKERSCOMP_WORKERS1;
		
		private System.Nullable<decimal> _WORKERSCOMP_WORKERS2;
		
		private System.Nullable<decimal> _WORKERSCOMP_WORKERS3;
		
		private string _WORKERSCOMP_STATLIMIT;
		
		private System.Nullable<decimal> _EXCESS_LIABILITY1;
		
		private System.Nullable<decimal> _EXCESS_LIABILITY2;
		
		private System.Nullable<decimal> _EXCESS_LIABILITY3;
		
		private string _EXCESS_MULTILAYER;
		
		private System.Nullable<decimal> _SINKHOLE_PROPERTY;
		
		private System.Nullable<decimal> _SINKHOLE_DEDUCTIBLE;
		
		private System.Nullable<decimal> _SINKHOLE_COINSURANCE;
		
		private System.Nullable<decimal> _PROFLIAB_LIABILITY1;
		
		private System.Nullable<decimal> _PROFLIAB_LIABILITY2;
		
		private System.Nullable<decimal> _PROFLIAB_LIABILITY3;
		
		private System.Nullable<decimal> _POLLUTION_LIABILITY1;
		
		private System.Nullable<decimal> _POLLUTION_LIABILITY2;
		
		private System.Nullable<decimal> _POLLUTION_LIABILITY3;
		
		private System.Nullable<decimal> _CONTENTS_PROPERTY;
		
		private System.Nullable<decimal> _CONTENTS_DEDUCTIBLE;
		
		private System.Nullable<decimal> _CONTENTS_COINSURANCE;
		
		private string _INSURANCE_ID_BOILERMACH;
		
		private string _INSURANCE_ID_BUILDINGORD;
		
		private string _INSURANCE_ID_BUSNSINCOME;
		
		private string _INSURANCE_ID_CONTENTS;
		
		private string _INSURANCE_ID_EARTHQUAKE;
		
		private string _INSURANCE_ID_EXCESS;
		
		private string _INSURANCE_ID_FLOOD;
		
		private string _INSURANCE_ID_HAZARD;
		
		private string _INSURANCE_ID_LIABILITY;
		
		private string _INSURANCE_ID_TERRORISM;
		
		private string _INSURANCE_ID_WIND;
		
		private string _INSURANCE_ID_WORKERSCOMP;
		
		private string _PAYEE_NAME;
		
		private string _PAYEE_ADDRESS1;
		
		private string _PAYEE_CITY;
		
		private string _PAYEE_STATE;
		
		private string _PAYEE_ZIP;
		
		private System.Nullable<decimal> _AMOUNT_DUE;
		
		private string _PAYMENT_DUE_OR_CHECK_DATE;
		
		private string _POLICY_TYPE;
		
		private string _EntryFlag;
		
		private string _WorkID;
		
		private System.Nullable<System.DateTime> _InserTime;
		
		private string _REPLACEMENTVALUE;
		
		private string _REPLACEMENTCOST;
		
		private string _FLOODREPLACEMENTVALUE;
		
		private string _FLOODREPLACEMENTCOST;
		
		private string _NFIP_FLOOD_ZONE;
		
		private string _GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC;
		
		private string _UNITOWNER;
		
		private string _LIEN_HOLDER_NAME;
		
		private string _LIEN_HOLDER_ADDRESS1;
		
		private string _LIEN_HOLDER_CITY;
		
		private string _LIEN_HOLDER_STATE;
		
		private string _LIEN_HOLDER_ZIP;
		
		private string _DEL_INTEREST_LH;
		
		private string _OTHER_COLL_SERIAL_NUMBER;
		
		private string _OTHER_COLL_YEAR;
		
		private string _OTHER_COLL_MAKE;
		
		private string _OTHER_COLL_MODEL;
		
		private string _OTHER_COLL_ZIP;
		
		private System.Nullable<decimal> _FLDCONTENTS_PROPERTY;
		
		private System.Nullable<decimal> _FLDCONTENTS_DEDUCTIBLE;
		
		private System.Nullable<decimal> _FLDCONTENTS_COINSURANCE;
		
		private string _FLDCONTENTSREPLACEMENTVALUE;
		
		private string _FLDCONTENTSREPLACEMENTCOST;
		
		private string _NFIP_FLDCONTENTS_ZONE;
		
		private string _STIC;
		
		public his_tblData1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="Decimal(18,0) NOT NULL")]
		public decimal RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DataID
		{
			get
			{
				return this._DataID;
			}
			set
			{
				if ((this._DataID != value))
				{
					this._DataID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BATCH_INFO", DbType="VarChar(12)")]
		public string BATCH_INFO
		{
			get
			{
				return this._BATCH_INFO;
			}
			set
			{
				if ((this._BATCH_INFO != value))
				{
					this._BATCH_INFO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGE_FILE_NAME", DbType="VarChar(500)")]
		public string IMAGE_FILE_NAME
		{
			get
			{
				return this._IMAGE_FILE_NAME;
			}
			set
			{
				if ((this._IMAGE_FILE_NAME != value))
				{
					this._IMAGE_FILE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_COMPANY_NAME", DbType="VarChar(225)")]
		public string AGENT_COMPANY_NAME
		{
			get
			{
				return this._AGENT_COMPANY_NAME;
			}
			set
			{
				if ((this._AGENT_COMPANY_NAME != value))
				{
					this._AGENT_COMPANY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_FAX", DbType="VarChar(30)")]
		public string AGENT_FAX
		{
			get
			{
				return this._AGENT_FAX;
			}
			set
			{
				if ((this._AGENT_FAX != value))
				{
					this._AGENT_FAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_PERSON_NAME", DbType="VarChar(30)")]
		public string AGENT_PERSON_NAME
		{
			get
			{
				return this._AGENT_PERSON_NAME;
			}
			set
			{
				if ((this._AGENT_PERSON_NAME != value))
				{
					this._AGENT_PERSON_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_PHONE", DbType="VarChar(30)")]
		public string AGENT_PHONE
		{
			get
			{
				return this._AGENT_PHONE;
			}
			set
			{
				if ((this._AGENT_PHONE != value))
				{
					this._AGENT_PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_STATE", DbType="VarChar(10)")]
		public string AGENT_STATE
		{
			get
			{
				return this._AGENT_STATE;
			}
			set
			{
				if ((this._AGENT_STATE != value))
				{
					this._AGENT_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_ZIP", DbType="VarChar(30)")]
		public string AGENT_ZIP
		{
			get
			{
				return this._AGENT_ZIP;
			}
			set
			{
				if ((this._AGENT_ZIP != value))
				{
					this._AGENT_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCEL_DATE", DbType="VarChar(30)")]
		public string CANCEL_DATE
		{
			get
			{
				return this._CANCEL_DATE;
			}
			set
			{
				if ((this._CANCEL_DATE != value))
				{
					this._CANCEL_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCEL_PREMIUM_DUE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CANCEL_PREMIUM_DUE
		{
			get
			{
				return this._CANCEL_PREMIUM_DUE;
			}
			set
			{
				if ((this._CANCEL_PREMIUM_DUE != value))
				{
					this._CANCEL_PREMIUM_DUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCEL_PREMIUM_DUE_DATE", DbType="VarChar(30)")]
		public string CANCEL_PREMIUM_DUE_DATE
		{
			get
			{
				return this._CANCEL_PREMIUM_DUE_DATE;
			}
			set
			{
				if ((this._CANCEL_PREMIUM_DUE_DATE != value))
				{
					this._CANCEL_PREMIUM_DUE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANCEL_REASON", DbType="VarChar(30)")]
		public string CANCEL_REASON
		{
			get
			{
				return this._CANCEL_REASON;
			}
			set
			{
				if ((this._CANCEL_REASON != value))
				{
					this._CANCEL_REASON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARRIER_NAME", DbType="VarChar(200)")]
		public string CARRIER_NAME
		{
			get
			{
				return this._CARRIER_NAME;
			}
			set
			{
				if ((this._CARRIER_NAME != value))
				{
					this._CARRIER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_EFFECTIVE_DATE", DbType="VarChar(30)")]
		public string CHANGE_EFFECTIVE_DATE
		{
			get
			{
				return this._CHANGE_EFFECTIVE_DATE;
			}
			set
			{
				if ((this._CHANGE_EFFECTIVE_DATE != value))
				{
					this._CHANGE_EFFECTIVE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COINSURANCE_PERCENT", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> COINSURANCE_PERCENT
		{
			get
			{
				return this._COINSURANCE_PERCENT;
			}
			set
			{
				if ((this._COINSURANCE_PERCENT != value))
				{
					this._COINSURANCE_PERCENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTINUOUS_TO_CANCEL", DbType="VarChar(10)")]
		public string CONTINUOUS_TO_CANCEL
		{
			get
			{
				return this._CONTINUOUS_TO_CANCEL;
			}
			set
			{
				if ((this._CONTINUOUS_TO_CANCEL != value))
				{
					this._CONTINUOUS_TO_CANCEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> DEDUCTIBLE
		{
			get
			{
				return this._DEDUCTIBLE;
			}
			set
			{
				if ((this._DEDUCTIBLE != value))
				{
					this._DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_DATE", DbType="VarChar(30)")]
		public string DOCUMENT_DATE
		{
			get
			{
				return this._DOCUMENT_DATE;
			}
			set
			{
				if ((this._DOCUMENT_DATE != value))
				{
					this._DOCUMENT_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_ID", DbType="VarChar(50)")]
		public string DOCUMENT_ID
		{
			get
			{
				return this._DOCUMENT_ID;
			}
			set
			{
				if ((this._DOCUMENT_ID != value))
				{
					this._DOCUMENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EFFECTIVE_DATE", DbType="VarChar(30)")]
		public string EFFECTIVE_DATE
		{
			get
			{
				return this._EFFECTIVE_DATE;
			}
			set
			{
				if ((this._EFFECTIVE_DATE != value))
				{
					this._EFFECTIVE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXPIRE_DATE", DbType="VarChar(30)")]
		public string EXPIRE_DATE
		{
			get
			{
				return this._EXPIRE_DATE;
			}
			set
			{
				if ((this._EXPIRE_DATE != value))
				{
					this._EXPIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_AMOUNT", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> INSURANCE_AMOUNT
		{
			get
			{
				return this._INSURANCE_AMOUNT;
			}
			set
			{
				if ((this._INSURANCE_AMOUNT != value))
				{
					this._INSURANCE_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID", DbType="VarChar(50)")]
		public string INSURANCE_ID
		{
			get
			{
				return this._INSURANCE_ID;
			}
			set
			{
				if ((this._INSURANCE_ID != value))
				{
					this._INSURANCE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_LOCATION_NUMBER", DbType="VarChar(12)")]
		public string INSURED_LOCATION_NUMBER
		{
			get
			{
				return this._INSURED_LOCATION_NUMBER;
			}
			set
			{
				if ((this._INSURED_LOCATION_NUMBER != value))
				{
					this._INSURED_LOCATION_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_LOCATION_OR_VEH_NUMBER", DbType="VarChar(12)")]
		public string INSURED_LOCATION_OR_VEH_NUMBER
		{
			get
			{
				return this._INSURED_LOCATION_OR_VEH_NUMBER;
			}
			set
			{
				if ((this._INSURED_LOCATION_OR_VEH_NUMBER != value))
				{
					this._INSURED_LOCATION_OR_VEH_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_MAIL_ADDRESS1", DbType="VarChar(225)")]
		public string INSURED_MAIL_ADDRESS1
		{
			get
			{
				return this._INSURED_MAIL_ADDRESS1;
			}
			set
			{
				if ((this._INSURED_MAIL_ADDRESS1 != value))
				{
					this._INSURED_MAIL_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_MAIL_ADDRESS2", DbType="VarChar(40)")]
		public string INSURED_MAIL_ADDRESS2
		{
			get
			{
				return this._INSURED_MAIL_ADDRESS2;
			}
			set
			{
				if ((this._INSURED_MAIL_ADDRESS2 != value))
				{
					this._INSURED_MAIL_ADDRESS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_MAIL_CITY", DbType="VarChar(30)")]
		public string INSURED_MAIL_CITY
		{
			get
			{
				return this._INSURED_MAIL_CITY;
			}
			set
			{
				if ((this._INSURED_MAIL_CITY != value))
				{
					this._INSURED_MAIL_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_MAIL_STATE", DbType="VarChar(10)")]
		public string INSURED_MAIL_STATE
		{
			get
			{
				return this._INSURED_MAIL_STATE;
			}
			set
			{
				if ((this._INSURED_MAIL_STATE != value))
				{
					this._INSURED_MAIL_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_MAIL_ZIP", DbType="VarChar(30)")]
		public string INSURED_MAIL_ZIP
		{
			get
			{
				return this._INSURED_MAIL_ZIP;
			}
			set
			{
				if ((this._INSURED_MAIL_ZIP != value))
				{
					this._INSURED_MAIL_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURED_NAME", DbType="VarChar(225)")]
		public string INSURED_NAME
		{
			get
			{
				return this._INSURED_NAME;
			}
			set
			{
				if ((this._INSURED_NAME != value))
				{
					this._INSURED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAN_NUMBER", DbType="VarChar(225)")]
		public string LOAN_NUMBER
		{
			get
			{
				return this._LOAN_NUMBER;
			}
			set
			{
				if ((this._LOAN_NUMBER != value))
				{
					this._LOAN_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSS_PAYEE_ADDRESS1", DbType="VarChar(225)")]
		public string LOSS_PAYEE_ADDRESS1
		{
			get
			{
				return this._LOSS_PAYEE_ADDRESS1;
			}
			set
			{
				if ((this._LOSS_PAYEE_ADDRESS1 != value))
				{
					this._LOSS_PAYEE_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSS_PAYEE_ADDRESS2", DbType="VarChar(40)")]
		public string LOSS_PAYEE_ADDRESS2
		{
			get
			{
				return this._LOSS_PAYEE_ADDRESS2;
			}
			set
			{
				if ((this._LOSS_PAYEE_ADDRESS2 != value))
				{
					this._LOSS_PAYEE_ADDRESS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSS_PAYEE_CITY", DbType="VarChar(30)")]
		public string LOSS_PAYEE_CITY
		{
			get
			{
				return this._LOSS_PAYEE_CITY;
			}
			set
			{
				if ((this._LOSS_PAYEE_CITY != value))
				{
					this._LOSS_PAYEE_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSS_PAYEE_NAME", DbType="VarChar(225)")]
		public string LOSS_PAYEE_NAME
		{
			get
			{
				return this._LOSS_PAYEE_NAME;
			}
			set
			{
				if ((this._LOSS_PAYEE_NAME != value))
				{
					this._LOSS_PAYEE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSS_PAYEE_STATE", DbType="VarChar(10)")]
		public string LOSS_PAYEE_STATE
		{
			get
			{
				return this._LOSS_PAYEE_STATE;
			}
			set
			{
				if ((this._LOSS_PAYEE_STATE != value))
				{
					this._LOSS_PAYEE_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSS_PAYEE_ZIP", DbType="VarChar(30)")]
		public string LOSS_PAYEE_ZIP
		{
			get
			{
				return this._LOSS_PAYEE_ZIP;
			}
			set
			{
				if ((this._LOSS_PAYEE_ZIP != value))
				{
					this._LOSS_PAYEE_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_NUMBER", DbType="VarChar(225)")]
		public string POLICY_NUMBER
		{
			get
			{
				return this._POLICY_NUMBER;
			}
			set
			{
				if ((this._POLICY_NUMBER != value))
				{
					this._POLICY_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREMIUM_AMOUNT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PREMIUM_AMOUNT
		{
			get
			{
				return this._PREMIUM_AMOUNT;
			}
			set
			{
				if ((this._PREMIUM_AMOUNT != value))
				{
					this._PREMIUM_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMOFUNITS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> NUMOFUNITS
		{
			get
			{
				return this._NUMOFUNITS;
			}
			set
			{
				if ((this._NUMOFUNITS != value))
				{
					this._NUMOFUNITS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REALESTATE_ADDRESS1", DbType="VarChar(225)")]
		public string REALESTATE_ADDRESS1
		{
			get
			{
				return this._REALESTATE_ADDRESS1;
			}
			set
			{
				if ((this._REALESTATE_ADDRESS1 != value))
				{
					this._REALESTATE_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REALESTATE_ADDRESS2", DbType="VarChar(40)")]
		public string REALESTATE_ADDRESS2
		{
			get
			{
				return this._REALESTATE_ADDRESS2;
			}
			set
			{
				if ((this._REALESTATE_ADDRESS2 != value))
				{
					this._REALESTATE_ADDRESS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REALESTATE_CITY", DbType="VarChar(30)")]
		public string REALESTATE_CITY
		{
			get
			{
				return this._REALESTATE_CITY;
			}
			set
			{
				if ((this._REALESTATE_CITY != value))
				{
					this._REALESTATE_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REALESTATE_STATE", DbType="VarChar(10)")]
		public string REALESTATE_STATE
		{
			get
			{
				return this._REALESTATE_STATE;
			}
			set
			{
				if ((this._REALESTATE_STATE != value))
				{
					this._REALESTATE_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REALESTATE_ZIP", DbType="VarChar(30)")]
		public string REALESTATE_ZIP
		{
			get
			{
				return this._REALESTATE_ZIP;
			}
			set
			{
				if ((this._REALESTATE_ZIP != value))
				{
					this._REALESTATE_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REINSTATE_DATE", DbType="VarChar(30)")]
		public string REINSTATE_DATE
		{
			get
			{
				return this._REINSTATE_DATE;
			}
			set
			{
				if ((this._REINSTATE_DATE != value))
				{
					this._REINSTATE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REINSTATE_WITHOUT_LAPSE", DbType="VarChar(10)")]
		public string REINSTATE_WITHOUT_LAPSE
		{
			get
			{
				return this._REINSTATE_WITHOUT_LAPSE;
			}
			set
			{
				if ((this._REINSTATE_WITHOUT_LAPSE != value))
				{
					this._REINSTATE_WITHOUT_LAPSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERM", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> TERM
		{
			get
			{
				return this._TERM;
			}
			set
			{
				if ((this._TERM != value))
				{
					this._TERM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHO_PAYS_PREMIUM", DbType="VarChar(30)")]
		public string WHO_PAYS_PREMIUM
		{
			get
			{
				return this._WHO_PAYS_PREMIUM;
			}
			set
			{
				if ((this._WHO_PAYS_PREMIUM != value))
				{
					this._WHO_PAYS_PREMIUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WINDHAILDED", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WINDHAILDED
		{
			get
			{
				return this._WINDHAILDED;
			}
			set
			{
				if ((this._WINDHAILDED != value))
				{
					this._WINDHAILDED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_ADDRESS", DbType="VarChar(225)")]
		public string AGENT_ADDRESS
		{
			get
			{
				return this._AGENT_ADDRESS;
			}
			set
			{
				if ((this._AGENT_ADDRESS != value))
				{
					this._AGENT_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGENT_CITY", DbType="VarChar(30)")]
		public string AGENT_CITY
		{
			get
			{
				return this._AGENT_CITY;
			}
			set
			{
				if ((this._AGENT_CITY != value))
				{
					this._AGENT_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_SIGNED", DbType="VarChar(10)")]
		public string DOCUMENT_SIGNED
		{
			get
			{
				return this._DOCUMENT_SIGNED;
			}
			set
			{
				if ((this._DOCUMENT_SIGNED != value))
				{
					this._DOCUMENT_SIGNED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANGE_ADDRESS", DbType="VarChar(50)")]
		public string RANGE_ADDRESS
		{
			get
			{
				return this._RANGE_ADDRESS;
			}
			set
			{
				if ((this._RANGE_ADDRESS != value))
				{
					this._RANGE_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_10DAYNONPAYNOTICE", DbType="VarChar(10)")]
		public string POLICY_10DAYNONPAYNOTICE
		{
			get
			{
				return this._POLICY_10DAYNONPAYNOTICE;
			}
			set
			{
				if ((this._POLICY_10DAYNONPAYNOTICE != value))
				{
					this._POLICY_10DAYNONPAYNOTICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_30DAYCANCELNOTICE", DbType="VarChar(10)")]
		public string POLICY_30DAYCANCELNOTICE
		{
			get
			{
				return this._POLICY_30DAYCANCELNOTICE;
			}
			set
			{
				if ((this._POLICY_30DAYCANCELNOTICE != value))
				{
					this._POLICY_30DAYCANCELNOTICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_CONTTOCANC", DbType="VarChar(10)")]
		public string POLICY_CONTTOCANC
		{
			get
			{
				return this._POLICY_CONTTOCANC;
			}
			set
			{
				if ((this._POLICY_CONTTOCANC != value))
				{
					this._POLICY_CONTTOCANC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_CUTTHROUGHENDORSE", DbType="VarChar(10)")]
		public string POLICY_CUTTHROUGHENDORSE
		{
			get
			{
				return this._POLICY_CUTTHROUGHENDORSE;
			}
			set
			{
				if ((this._POLICY_CUTTHROUGHENDORSE != value))
				{
					this._POLICY_CUTTHROUGHENDORSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_DISCLOSUREFORMREC", DbType="VarChar(10)")]
		public string POLICY_DISCLOSUREFORMREC
		{
			get
			{
				return this._POLICY_DISCLOSUREFORMREC;
			}
			set
			{
				if ((this._POLICY_DISCLOSUREFORMREC != value))
				{
					this._POLICY_DISCLOSUREFORMREC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_INSPAYSPREMIUM", DbType="VarChar(10)")]
		public string POLICY_INSPAYSPREMIUM
		{
			get
			{
				return this._POLICY_INSPAYSPREMIUM;
			}
			set
			{
				if ((this._POLICY_INSPAYSPREMIUM != value))
				{
					this._POLICY_INSPAYSPREMIUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_MOLDINCLUDE", DbType="VarChar(10)")]
		public string POLICY_MOLDINCLUDE
		{
			get
			{
				return this._POLICY_MOLDINCLUDE;
			}
			set
			{
				if ((this._POLICY_MOLDINCLUDE != value))
				{
					this._POLICY_MOLDINCLUDE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_RISKPURCHASINGGROUP", DbType="VarChar(10)")]
		public string POLICY_RISKPURCHASINGGROUP
		{
			get
			{
				return this._POLICY_RISKPURCHASINGGROUP;
			}
			set
			{
				if ((this._POLICY_RISKPURCHASINGGROUP != value))
				{
					this._POLICY_RISKPURCHASINGGROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_TENANTPROVIDED", DbType="VarChar(10)")]
		public string POLICY_TENANTPROVIDED
		{
			get
			{
				return this._POLICY_TENANTPROVIDED;
			}
			set
			{
				if ((this._POLICY_TENANTPROVIDED != value))
				{
					this._POLICY_TENANTPROVIDED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_TERRORINCLUDE", DbType="VarChar(10)")]
		public string POLICY_TERRORINCLUDE
		{
			get
			{
				return this._POLICY_TERRORINCLUDE;
			}
			set
			{
				if ((this._POLICY_TERRORINCLUDE != value))
				{
					this._POLICY_TERRORINCLUDE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="VarChar(255)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this._NOTES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDTNL_INSURED_NAME", DbType="VarChar(225)")]
		public string ADDTNL_INSURED_NAME
		{
			get
			{
				return this._ADDTNL_INSURED_NAME;
			}
			set
			{
				if ((this._ADDTNL_INSURED_NAME != value))
				{
					this._ADDTNL_INSURED_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDTNL_INSURED_ADDRESS1", DbType="VarChar(225)")]
		public string ADDTNL_INSURED_ADDRESS1
		{
			get
			{
				return this._ADDTNL_INSURED_ADDRESS1;
			}
			set
			{
				if ((this._ADDTNL_INSURED_ADDRESS1 != value))
				{
					this._ADDTNL_INSURED_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDTNL_INSURED_CITY", DbType="VarChar(30)")]
		public string ADDTNL_INSURED_CITY
		{
			get
			{
				return this._ADDTNL_INSURED_CITY;
			}
			set
			{
				if ((this._ADDTNL_INSURED_CITY != value))
				{
					this._ADDTNL_INSURED_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDTNL_INSURED_STATE", DbType="VarChar(30)")]
		public string ADDTNL_INSURED_STATE
		{
			get
			{
				return this._ADDTNL_INSURED_STATE;
			}
			set
			{
				if ((this._ADDTNL_INSURED_STATE != value))
				{
					this._ADDTNL_INSURED_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDTNL_INSURED_ZIP", DbType="VarChar(30)")]
		public string ADDTNL_INSURED_ZIP
		{
			get
			{
				return this._ADDTNL_INSURED_ZIP;
			}
			set
			{
				if ((this._ADDTNL_INSURED_ZIP != value))
				{
					this._ADDTNL_INSURED_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL_INTEREST_AI", DbType="VarChar(10)")]
		public string DEL_INTEREST_AI
		{
			get
			{
				return this._DEL_INTEREST_AI;
			}
			set
			{
				if ((this._DEL_INTEREST_AI != value))
				{
					this._DEL_INTEREST_AI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> HAZARD_PROPERTY
		{
			get
			{
				return this._HAZARD_PROPERTY;
			}
			set
			{
				if ((this._HAZARD_PROPERTY != value))
				{
					this._HAZARD_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> HAZARD_DEDUCTIBLE
		{
			get
			{
				return this._HAZARD_DEDUCTIBLE;
			}
			set
			{
				if ((this._HAZARD_DEDUCTIBLE != value))
				{
					this._HAZARD_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_WINDHAILDED", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> HAZARD_WINDHAILDED
		{
			get
			{
				return this._HAZARD_WINDHAILDED;
			}
			set
			{
				if ((this._HAZARD_WINDHAILDED != value))
				{
					this._HAZARD_WINDHAILDED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> HAZARD_COINSURANCE
		{
			get
			{
				return this._HAZARD_COINSURANCE;
			}
			set
			{
				if ((this._HAZARD_COINSURANCE != value))
				{
					this._HAZARD_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_ACV", DbType="VarChar(10)")]
		public string HAZARD_ACV
		{
			get
			{
				return this._HAZARD_ACV;
			}
			set
			{
				if ((this._HAZARD_ACV != value))
				{
					this._HAZARD_ACV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_AGREEDAMNTVAL", DbType="VarChar(10)")]
		public string HAZARD_AGREEDAMNTVAL
		{
			get
			{
				return this._HAZARD_AGREEDAMNTVAL;
			}
			set
			{
				if ((this._HAZARD_AGREEDAMNTVAL != value))
				{
					this._HAZARD_AGREEDAMNTVAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_ALLRISK", DbType="VarChar(10)")]
		public string HAZARD_ALLRISK
		{
			get
			{
				return this._HAZARD_ALLRISK;
			}
			set
			{
				if ((this._HAZARD_ALLRISK != value))
				{
					this._HAZARD_ALLRISK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_BLANKETPOLLIMIT", DbType="VarChar(10)")]
		public string HAZARD_BLANKETPOLLIMIT
		{
			get
			{
				return this._HAZARD_BLANKETPOLLIMIT;
			}
			set
			{
				if ((this._HAZARD_BLANKETPOLLIMIT != value))
				{
					this._HAZARD_BLANKETPOLLIMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_MULTILAYER", DbType="VarChar(10)")]
		public string HAZARD_MULTILAYER
		{
			get
			{
				return this._HAZARD_MULTILAYER;
			}
			set
			{
				if ((this._HAZARD_MULTILAYER != value))
				{
					this._HAZARD_MULTILAYER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_RC", DbType="VarChar(10)")]
		public string HAZARD_RC
		{
			get
			{
				return this._HAZARD_RC;
			}
			set
			{
				if ((this._HAZARD_RC != value))
				{
					this._HAZARD_RC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_WAIVEROFSUBJ", DbType="VarChar(10)")]
		public string HAZARD_WAIVEROFSUBJ
		{
			get
			{
				return this._HAZARD_WAIVEROFSUBJ;
			}
			set
			{
				if ((this._HAZARD_WAIVEROFSUBJ != value))
				{
					this._HAZARD_WAIVEROFSUBJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAZARD_WINDEXCLUDED", DbType="VarChar(10)")]
		public string HAZARD_WINDEXCLUDED
		{
			get
			{
				return this._HAZARD_WINDEXCLUDED;
			}
			set
			{
				if ((this._HAZARD_WINDEXCLUDED != value))
				{
					this._HAZARD_WINDEXCLUDED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIABILITY_LIABILITY1", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> LIABILITY_LIABILITY1
		{
			get
			{
				return this._LIABILITY_LIABILITY1;
			}
			set
			{
				if ((this._LIABILITY_LIABILITY1 != value))
				{
					this._LIABILITY_LIABILITY1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIABILITY_LIABILITY2", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> LIABILITY_LIABILITY2
		{
			get
			{
				return this._LIABILITY_LIABILITY2;
			}
			set
			{
				if ((this._LIABILITY_LIABILITY2 != value))
				{
					this._LIABILITY_LIABILITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIABILITY_LIABILITY3", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> LIABILITY_LIABILITY3
		{
			get
			{
				return this._LIABILITY_LIABILITY3;
			}
			set
			{
				if ((this._LIABILITY_LIABILITY3 != value))
				{
					this._LIABILITY_LIABILITY3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIABILITY_DLGENADDLIM", DbType="VarChar(10)")]
		public string LIABILITY_DLGENADDLIM
		{
			get
			{
				return this._LIABILITY_DLGENADDLIM;
			}
			set
			{
				if ((this._LIABILITY_DLGENADDLIM != value))
				{
					this._LIABILITY_DLGENADDLIM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_AMOUNT", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BUSNSINCOME_AMOUNT
		{
			get
			{
				return this._BUSNSINCOME_AMOUNT;
			}
			set
			{
				if ((this._BUSNSINCOME_AMOUNT != value))
				{
					this._BUSNSINCOME_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_EXTRAEXPENSE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BUSNSINCOME_EXTRAEXPENSE
		{
			get
			{
				return this._BUSNSINCOME_EXTRAEXPENSE;
			}
			set
			{
				if ((this._BUSNSINCOME_EXTRAEXPENSE != value))
				{
					this._BUSNSINCOME_EXTRAEXPENSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BUSNSINCOME_COINSURANCE
		{
			get
			{
				return this._BUSNSINCOME_COINSURANCE;
			}
			set
			{
				if ((this._BUSNSINCOME_COINSURANCE != value))
				{
					this._BUSNSINCOME_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_6MOINDEMNITY", DbType="VarChar(10)")]
		public string BUSNSINCOME_6MOINDEMNITY
		{
			get
			{
				return this._BUSNSINCOME_6MOINDEMNITY;
			}
			set
			{
				if ((this._BUSNSINCOME_6MOINDEMNITY != value))
				{
					this._BUSNSINCOME_6MOINDEMNITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_12MOINDEMNITY", DbType="VarChar(10)")]
		public string BUSNSINCOME_12MOINDEMNITY
		{
			get
			{
				return this._BUSNSINCOME_12MOINDEMNITY;
			}
			set
			{
				if ((this._BUSNSINCOME_12MOINDEMNITY != value))
				{
					this._BUSNSINCOME_12MOINDEMNITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_18MOINDEMNITY", DbType="VarChar(10)")]
		public string BUSNSINCOME_18MOINDEMNITY
		{
			get
			{
				return this._BUSNSINCOME_18MOINDEMNITY;
			}
			set
			{
				if ((this._BUSNSINCOME_18MOINDEMNITY != value))
				{
					this._BUSNSINCOME_18MOINDEMNITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_24MOINDEMNITY", DbType="VarChar(10)")]
		public string BUSNSINCOME_24MOINDEMNITY
		{
			get
			{
				return this._BUSNSINCOME_24MOINDEMNITY;
			}
			set
			{
				if ((this._BUSNSINCOME_24MOINDEMNITY != value))
				{
					this._BUSNSINCOME_24MOINDEMNITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUSNSINCOME_ACTUALLOSSSUST", DbType="VarChar(10)")]
		public string BUSNSINCOME_ACTUALLOSSSUST
		{
			get
			{
				return this._BUSNSINCOME_ACTUALLOSSSUST;
			}
			set
			{
				if ((this._BUSNSINCOME_ACTUALLOSSSUST != value))
				{
					this._BUSNSINCOME_ACTUALLOSSSUST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDINGORD_PROPUNDMG", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BUILDINGORD_PROPUNDMG
		{
			get
			{
				return this._BUILDINGORD_PROPUNDMG;
			}
			set
			{
				if ((this._BUILDINGORD_PROPUNDMG != value))
				{
					this._BUILDINGORD_PROPUNDMG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDINGORD_DEMOCOST", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BUILDINGORD_DEMOCOST
		{
			get
			{
				return this._BUILDINGORD_DEMOCOST;
			}
			set
			{
				if ((this._BUILDINGORD_DEMOCOST != value))
				{
					this._BUILDINGORD_DEMOCOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDINGORD_INCRCOST", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BUILDINGORD_INCRCOST
		{
			get
			{
				return this._BUILDINGORD_INCRCOST;
			}
			set
			{
				if ((this._BUILDINGORD_INCRCOST != value))
				{
					this._BUILDINGORD_INCRCOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDINGORD_DEMOLITION", DbType="VarChar(10)")]
		public string BUILDINGORD_DEMOLITION
		{
			get
			{
				return this._BUILDINGORD_DEMOLITION;
			}
			set
			{
				if ((this._BUILDINGORD_DEMOLITION != value))
				{
					this._BUILDINGORD_DEMOLITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUILDINGORD_INCREASECONSTRCOST", DbType="VarChar(10)")]
		public string BUILDINGORD_INCREASECONSTRCOST
		{
			get
			{
				return this._BUILDINGORD_INCREASECONSTRCOST;
			}
			set
			{
				if ((this._BUILDINGORD_INCREASECONSTRCOST != value))
				{
					this._BUILDINGORD_INCREASECONSTRCOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOILERMACH_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BOILERMACH_PROPERTY
		{
			get
			{
				return this._BOILERMACH_PROPERTY;
			}
			set
			{
				if ((this._BOILERMACH_PROPERTY != value))
				{
					this._BOILERMACH_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOILERMACH_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BOILERMACH_DEDUCTIBLE
		{
			get
			{
				return this._BOILERMACH_DEDUCTIBLE;
			}
			set
			{
				if ((this._BOILERMACH_DEDUCTIBLE != value))
				{
					this._BOILERMACH_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOILERMACH_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BOILERMACH_COINSURANCE
		{
			get
			{
				return this._BOILERMACH_COINSURANCE;
			}
			set
			{
				if ((this._BOILERMACH_COINSURANCE != value))
				{
					this._BOILERMACH_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRORISM_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> TERRORISM_PROPERTY
		{
			get
			{
				return this._TERRORISM_PROPERTY;
			}
			set
			{
				if ((this._TERRORISM_PROPERTY != value))
				{
					this._TERRORISM_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRORISM_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> TERRORISM_DEDUCTIBLE
		{
			get
			{
				return this._TERRORISM_DEDUCTIBLE;
			}
			set
			{
				if ((this._TERRORISM_DEDUCTIBLE != value))
				{
					this._TERRORISM_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERRORISM_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> TERRORISM_COINSURANCE
		{
			get
			{
				return this._TERRORISM_COINSURANCE;
			}
			set
			{
				if ((this._TERRORISM_COINSURANCE != value))
				{
					this._TERRORISM_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EARTHQUAKE_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> EARTHQUAKE_PROPERTY
		{
			get
			{
				return this._EARTHQUAKE_PROPERTY;
			}
			set
			{
				if ((this._EARTHQUAKE_PROPERTY != value))
				{
					this._EARTHQUAKE_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EARTHQUAKE_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> EARTHQUAKE_DEDUCTIBLE
		{
			get
			{
				return this._EARTHQUAKE_DEDUCTIBLE;
			}
			set
			{
				if ((this._EARTHQUAKE_DEDUCTIBLE != value))
				{
					this._EARTHQUAKE_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EARTHQUAKE_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> EARTHQUAKE_COINSURANCE
		{
			get
			{
				return this._EARTHQUAKE_COINSURANCE;
			}
			set
			{
				if ((this._EARTHQUAKE_COINSURANCE != value))
				{
					this._EARTHQUAKE_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIND_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WIND_PROPERTY
		{
			get
			{
				return this._WIND_PROPERTY;
			}
			set
			{
				if ((this._WIND_PROPERTY != value))
				{
					this._WIND_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIND_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WIND_DEDUCTIBLE
		{
			get
			{
				return this._WIND_DEDUCTIBLE;
			}
			set
			{
				if ((this._WIND_DEDUCTIBLE != value))
				{
					this._WIND_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIND_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WIND_COINSURANCE
		{
			get
			{
				return this._WIND_COINSURANCE;
			}
			set
			{
				if ((this._WIND_COINSURANCE != value))
				{
					this._WIND_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLOOD_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FLOOD_PROPERTY
		{
			get
			{
				return this._FLOOD_PROPERTY;
			}
			set
			{
				if ((this._FLOOD_PROPERTY != value))
				{
					this._FLOOD_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLOOD_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FLOOD_DEDUCTIBLE
		{
			get
			{
				return this._FLOOD_DEDUCTIBLE;
			}
			set
			{
				if ((this._FLOOD_DEDUCTIBLE != value))
				{
					this._FLOOD_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLOOD_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FLOOD_COINSURANCE
		{
			get
			{
				return this._FLOOD_COINSURANCE;
			}
			set
			{
				if ((this._FLOOD_COINSURANCE != value))
				{
					this._FLOOD_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKERSCOMP_WORKERS1", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WORKERSCOMP_WORKERS1
		{
			get
			{
				return this._WORKERSCOMP_WORKERS1;
			}
			set
			{
				if ((this._WORKERSCOMP_WORKERS1 != value))
				{
					this._WORKERSCOMP_WORKERS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKERSCOMP_WORKERS2", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WORKERSCOMP_WORKERS2
		{
			get
			{
				return this._WORKERSCOMP_WORKERS2;
			}
			set
			{
				if ((this._WORKERSCOMP_WORKERS2 != value))
				{
					this._WORKERSCOMP_WORKERS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKERSCOMP_WORKERS3", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> WORKERSCOMP_WORKERS3
		{
			get
			{
				return this._WORKERSCOMP_WORKERS3;
			}
			set
			{
				if ((this._WORKERSCOMP_WORKERS3 != value))
				{
					this._WORKERSCOMP_WORKERS3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKERSCOMP_STATLIMIT", DbType="VarChar(50)")]
		public string WORKERSCOMP_STATLIMIT
		{
			get
			{
				return this._WORKERSCOMP_STATLIMIT;
			}
			set
			{
				if ((this._WORKERSCOMP_STATLIMIT != value))
				{
					this._WORKERSCOMP_STATLIMIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXCESS_LIABILITY1", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> EXCESS_LIABILITY1
		{
			get
			{
				return this._EXCESS_LIABILITY1;
			}
			set
			{
				if ((this._EXCESS_LIABILITY1 != value))
				{
					this._EXCESS_LIABILITY1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXCESS_LIABILITY2", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> EXCESS_LIABILITY2
		{
			get
			{
				return this._EXCESS_LIABILITY2;
			}
			set
			{
				if ((this._EXCESS_LIABILITY2 != value))
				{
					this._EXCESS_LIABILITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXCESS_LIABILITY3", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> EXCESS_LIABILITY3
		{
			get
			{
				return this._EXCESS_LIABILITY3;
			}
			set
			{
				if ((this._EXCESS_LIABILITY3 != value))
				{
					this._EXCESS_LIABILITY3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXCESS_MULTILAYER", DbType="VarChar(50)")]
		public string EXCESS_MULTILAYER
		{
			get
			{
				return this._EXCESS_MULTILAYER;
			}
			set
			{
				if ((this._EXCESS_MULTILAYER != value))
				{
					this._EXCESS_MULTILAYER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINKHOLE_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> SINKHOLE_PROPERTY
		{
			get
			{
				return this._SINKHOLE_PROPERTY;
			}
			set
			{
				if ((this._SINKHOLE_PROPERTY != value))
				{
					this._SINKHOLE_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINKHOLE_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> SINKHOLE_DEDUCTIBLE
		{
			get
			{
				return this._SINKHOLE_DEDUCTIBLE;
			}
			set
			{
				if ((this._SINKHOLE_DEDUCTIBLE != value))
				{
					this._SINKHOLE_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SINKHOLE_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> SINKHOLE_COINSURANCE
		{
			get
			{
				return this._SINKHOLE_COINSURANCE;
			}
			set
			{
				if ((this._SINKHOLE_COINSURANCE != value))
				{
					this._SINKHOLE_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFLIAB_LIABILITY1", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> PROFLIAB_LIABILITY1
		{
			get
			{
				return this._PROFLIAB_LIABILITY1;
			}
			set
			{
				if ((this._PROFLIAB_LIABILITY1 != value))
				{
					this._PROFLIAB_LIABILITY1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFLIAB_LIABILITY2", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> PROFLIAB_LIABILITY2
		{
			get
			{
				return this._PROFLIAB_LIABILITY2;
			}
			set
			{
				if ((this._PROFLIAB_LIABILITY2 != value))
				{
					this._PROFLIAB_LIABILITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFLIAB_LIABILITY3", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> PROFLIAB_LIABILITY3
		{
			get
			{
				return this._PROFLIAB_LIABILITY3;
			}
			set
			{
				if ((this._PROFLIAB_LIABILITY3 != value))
				{
					this._PROFLIAB_LIABILITY3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLLUTION_LIABILITY1", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> POLLUTION_LIABILITY1
		{
			get
			{
				return this._POLLUTION_LIABILITY1;
			}
			set
			{
				if ((this._POLLUTION_LIABILITY1 != value))
				{
					this._POLLUTION_LIABILITY1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLLUTION_LIABILITY2", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> POLLUTION_LIABILITY2
		{
			get
			{
				return this._POLLUTION_LIABILITY2;
			}
			set
			{
				if ((this._POLLUTION_LIABILITY2 != value))
				{
					this._POLLUTION_LIABILITY2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLLUTION_LIABILITY3", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> POLLUTION_LIABILITY3
		{
			get
			{
				return this._POLLUTION_LIABILITY3;
			}
			set
			{
				if ((this._POLLUTION_LIABILITY3 != value))
				{
					this._POLLUTION_LIABILITY3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENTS_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> CONTENTS_PROPERTY
		{
			get
			{
				return this._CONTENTS_PROPERTY;
			}
			set
			{
				if ((this._CONTENTS_PROPERTY != value))
				{
					this._CONTENTS_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENTS_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> CONTENTS_DEDUCTIBLE
		{
			get
			{
				return this._CONTENTS_DEDUCTIBLE;
			}
			set
			{
				if ((this._CONTENTS_DEDUCTIBLE != value))
				{
					this._CONTENTS_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENTS_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> CONTENTS_COINSURANCE
		{
			get
			{
				return this._CONTENTS_COINSURANCE;
			}
			set
			{
				if ((this._CONTENTS_COINSURANCE != value))
				{
					this._CONTENTS_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_BOILERMACH", DbType="VarChar(10)")]
		public string INSURANCE_ID_BOILERMACH
		{
			get
			{
				return this._INSURANCE_ID_BOILERMACH;
			}
			set
			{
				if ((this._INSURANCE_ID_BOILERMACH != value))
				{
					this._INSURANCE_ID_BOILERMACH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_BUILDINGORD", DbType="VarChar(10)")]
		public string INSURANCE_ID_BUILDINGORD
		{
			get
			{
				return this._INSURANCE_ID_BUILDINGORD;
			}
			set
			{
				if ((this._INSURANCE_ID_BUILDINGORD != value))
				{
					this._INSURANCE_ID_BUILDINGORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_BUSNSINCOME", DbType="VarChar(10)")]
		public string INSURANCE_ID_BUSNSINCOME
		{
			get
			{
				return this._INSURANCE_ID_BUSNSINCOME;
			}
			set
			{
				if ((this._INSURANCE_ID_BUSNSINCOME != value))
				{
					this._INSURANCE_ID_BUSNSINCOME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_CONTENTS", DbType="VarChar(10)")]
		public string INSURANCE_ID_CONTENTS
		{
			get
			{
				return this._INSURANCE_ID_CONTENTS;
			}
			set
			{
				if ((this._INSURANCE_ID_CONTENTS != value))
				{
					this._INSURANCE_ID_CONTENTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_EARTHQUAKE", DbType="VarChar(10)")]
		public string INSURANCE_ID_EARTHQUAKE
		{
			get
			{
				return this._INSURANCE_ID_EARTHQUAKE;
			}
			set
			{
				if ((this._INSURANCE_ID_EARTHQUAKE != value))
				{
					this._INSURANCE_ID_EARTHQUAKE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_EXCESS", DbType="VarChar(10)")]
		public string INSURANCE_ID_EXCESS
		{
			get
			{
				return this._INSURANCE_ID_EXCESS;
			}
			set
			{
				if ((this._INSURANCE_ID_EXCESS != value))
				{
					this._INSURANCE_ID_EXCESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_FLOOD", DbType="VarChar(10)")]
		public string INSURANCE_ID_FLOOD
		{
			get
			{
				return this._INSURANCE_ID_FLOOD;
			}
			set
			{
				if ((this._INSURANCE_ID_FLOOD != value))
				{
					this._INSURANCE_ID_FLOOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_HAZARD", DbType="VarChar(10)")]
		public string INSURANCE_ID_HAZARD
		{
			get
			{
				return this._INSURANCE_ID_HAZARD;
			}
			set
			{
				if ((this._INSURANCE_ID_HAZARD != value))
				{
					this._INSURANCE_ID_HAZARD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_LIABILITY", DbType="VarChar(10)")]
		public string INSURANCE_ID_LIABILITY
		{
			get
			{
				return this._INSURANCE_ID_LIABILITY;
			}
			set
			{
				if ((this._INSURANCE_ID_LIABILITY != value))
				{
					this._INSURANCE_ID_LIABILITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_TERRORISM", DbType="VarChar(10)")]
		public string INSURANCE_ID_TERRORISM
		{
			get
			{
				return this._INSURANCE_ID_TERRORISM;
			}
			set
			{
				if ((this._INSURANCE_ID_TERRORISM != value))
				{
					this._INSURANCE_ID_TERRORISM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_WIND", DbType="VarChar(10)")]
		public string INSURANCE_ID_WIND
		{
			get
			{
				return this._INSURANCE_ID_WIND;
			}
			set
			{
				if ((this._INSURANCE_ID_WIND != value))
				{
					this._INSURANCE_ID_WIND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSURANCE_ID_WORKERSCOMP", DbType="VarChar(10)")]
		public string INSURANCE_ID_WORKERSCOMP
		{
			get
			{
				return this._INSURANCE_ID_WORKERSCOMP;
			}
			set
			{
				if ((this._INSURANCE_ID_WORKERSCOMP != value))
				{
					this._INSURANCE_ID_WORKERSCOMP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYEE_NAME", DbType="VarChar(225)")]
		public string PAYEE_NAME
		{
			get
			{
				return this._PAYEE_NAME;
			}
			set
			{
				if ((this._PAYEE_NAME != value))
				{
					this._PAYEE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYEE_ADDRESS1", DbType="VarChar(225)")]
		public string PAYEE_ADDRESS1
		{
			get
			{
				return this._PAYEE_ADDRESS1;
			}
			set
			{
				if ((this._PAYEE_ADDRESS1 != value))
				{
					this._PAYEE_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYEE_CITY", DbType="VarChar(40)")]
		public string PAYEE_CITY
		{
			get
			{
				return this._PAYEE_CITY;
			}
			set
			{
				if ((this._PAYEE_CITY != value))
				{
					this._PAYEE_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYEE_STATE", DbType="VarChar(20)")]
		public string PAYEE_STATE
		{
			get
			{
				return this._PAYEE_STATE;
			}
			set
			{
				if ((this._PAYEE_STATE != value))
				{
					this._PAYEE_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYEE_ZIP", DbType="VarChar(50)")]
		public string PAYEE_ZIP
		{
			get
			{
				return this._PAYEE_ZIP;
			}
			set
			{
				if ((this._PAYEE_ZIP != value))
				{
					this._PAYEE_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT_DUE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> AMOUNT_DUE
		{
			get
			{
				return this._AMOUNT_DUE;
			}
			set
			{
				if ((this._AMOUNT_DUE != value))
				{
					this._AMOUNT_DUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT_DUE_OR_CHECK_DATE", DbType="VarChar(30)")]
		public string PAYMENT_DUE_OR_CHECK_DATE
		{
			get
			{
				return this._PAYMENT_DUE_OR_CHECK_DATE;
			}
			set
			{
				if ((this._PAYMENT_DUE_OR_CHECK_DATE != value))
				{
					this._PAYMENT_DUE_OR_CHECK_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLICY_TYPE", DbType="VarChar(50)")]
		public string POLICY_TYPE
		{
			get
			{
				return this._POLICY_TYPE;
			}
			set
			{
				if ((this._POLICY_TYPE != value))
				{
					this._POLICY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryFlag", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string EntryFlag
		{
			get
			{
				return this._EntryFlag;
			}
			set
			{
				if ((this._EntryFlag != value))
				{
					this._EntryFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string WorkID
		{
			get
			{
				return this._WorkID;
			}
			set
			{
				if ((this._WorkID != value))
				{
					this._WorkID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InserTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> InserTime
		{
			get
			{
				return this._InserTime;
			}
			set
			{
				if ((this._InserTime != value))
				{
					this._InserTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPLACEMENTVALUE", DbType="VarChar(20)")]
		public string REPLACEMENTVALUE
		{
			get
			{
				return this._REPLACEMENTVALUE;
			}
			set
			{
				if ((this._REPLACEMENTVALUE != value))
				{
					this._REPLACEMENTVALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPLACEMENTCOST", DbType="VarChar(5)")]
		public string REPLACEMENTCOST
		{
			get
			{
				return this._REPLACEMENTCOST;
			}
			set
			{
				if ((this._REPLACEMENTCOST != value))
				{
					this._REPLACEMENTCOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLOODREPLACEMENTVALUE", DbType="VarChar(20)")]
		public string FLOODREPLACEMENTVALUE
		{
			get
			{
				return this._FLOODREPLACEMENTVALUE;
			}
			set
			{
				if ((this._FLOODREPLACEMENTVALUE != value))
				{
					this._FLOODREPLACEMENTVALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLOODREPLACEMENTCOST", DbType="VarChar(5)")]
		public string FLOODREPLACEMENTCOST
		{
			get
			{
				return this._FLOODREPLACEMENTCOST;
			}
			set
			{
				if ((this._FLOODREPLACEMENTCOST != value))
				{
					this._FLOODREPLACEMENTCOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NFIP_FLOOD_ZONE", DbType="VarChar(200)")]
		public string NFIP_FLOOD_ZONE
		{
			get
			{
				return this._NFIP_FLOOD_ZONE;
			}
			set
			{
				if ((this._NFIP_FLOOD_ZONE != value))
				{
					this._NFIP_FLOOD_ZONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC", DbType="VarChar(200)")]
		public string GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC
		{
			get
			{
				return this._GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC;
			}
			set
			{
				if ((this._GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC != value))
				{
					this._GRANDFATHERED_FLOOD_ZONE_CHARACTERISTIC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITOWNER", DbType="VarChar(10)")]
		public string UNITOWNER
		{
			get
			{
				return this._UNITOWNER;
			}
			set
			{
				if ((this._UNITOWNER != value))
				{
					this._UNITOWNER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEN_HOLDER_NAME", DbType="VarChar(500)")]
		public string LIEN_HOLDER_NAME
		{
			get
			{
				return this._LIEN_HOLDER_NAME;
			}
			set
			{
				if ((this._LIEN_HOLDER_NAME != value))
				{
					this._LIEN_HOLDER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEN_HOLDER_ADDRESS1", DbType="VarChar(50)")]
		public string LIEN_HOLDER_ADDRESS1
		{
			get
			{
				return this._LIEN_HOLDER_ADDRESS1;
			}
			set
			{
				if ((this._LIEN_HOLDER_ADDRESS1 != value))
				{
					this._LIEN_HOLDER_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEN_HOLDER_CITY", DbType="VarChar(40)")]
		public string LIEN_HOLDER_CITY
		{
			get
			{
				return this._LIEN_HOLDER_CITY;
			}
			set
			{
				if ((this._LIEN_HOLDER_CITY != value))
				{
					this._LIEN_HOLDER_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEN_HOLDER_STATE", DbType="VarChar(20)")]
		public string LIEN_HOLDER_STATE
		{
			get
			{
				return this._LIEN_HOLDER_STATE;
			}
			set
			{
				if ((this._LIEN_HOLDER_STATE != value))
				{
					this._LIEN_HOLDER_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEN_HOLDER_ZIP", DbType="VarChar(50)")]
		public string LIEN_HOLDER_ZIP
		{
			get
			{
				return this._LIEN_HOLDER_ZIP;
			}
			set
			{
				if ((this._LIEN_HOLDER_ZIP != value))
				{
					this._LIEN_HOLDER_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEL_INTEREST_LH", DbType="VarChar(50)")]
		public string DEL_INTEREST_LH
		{
			get
			{
				return this._DEL_INTEREST_LH;
			}
			set
			{
				if ((this._DEL_INTEREST_LH != value))
				{
					this._DEL_INTEREST_LH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHER_COLL_SERIAL_NUMBER", DbType="VarChar(20)")]
		public string OTHER_COLL_SERIAL_NUMBER
		{
			get
			{
				return this._OTHER_COLL_SERIAL_NUMBER;
			}
			set
			{
				if ((this._OTHER_COLL_SERIAL_NUMBER != value))
				{
					this._OTHER_COLL_SERIAL_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHER_COLL_YEAR", DbType="VarChar(10)")]
		public string OTHER_COLL_YEAR
		{
			get
			{
				return this._OTHER_COLL_YEAR;
			}
			set
			{
				if ((this._OTHER_COLL_YEAR != value))
				{
					this._OTHER_COLL_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHER_COLL_MAKE", DbType="VarChar(30)")]
		public string OTHER_COLL_MAKE
		{
			get
			{
				return this._OTHER_COLL_MAKE;
			}
			set
			{
				if ((this._OTHER_COLL_MAKE != value))
				{
					this._OTHER_COLL_MAKE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHER_COLL_MODEL", DbType="VarChar(50)")]
		public string OTHER_COLL_MODEL
		{
			get
			{
				return this._OTHER_COLL_MODEL;
			}
			set
			{
				if ((this._OTHER_COLL_MODEL != value))
				{
					this._OTHER_COLL_MODEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHER_COLL_ZIP", DbType="VarChar(30)")]
		public string OTHER_COLL_ZIP
		{
			get
			{
				return this._OTHER_COLL_ZIP;
			}
			set
			{
				if ((this._OTHER_COLL_ZIP != value))
				{
					this._OTHER_COLL_ZIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLDCONTENTS_PROPERTY", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FLDCONTENTS_PROPERTY
		{
			get
			{
				return this._FLDCONTENTS_PROPERTY;
			}
			set
			{
				if ((this._FLDCONTENTS_PROPERTY != value))
				{
					this._FLDCONTENTS_PROPERTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLDCONTENTS_DEDUCTIBLE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FLDCONTENTS_DEDUCTIBLE
		{
			get
			{
				return this._FLDCONTENTS_DEDUCTIBLE;
			}
			set
			{
				if ((this._FLDCONTENTS_DEDUCTIBLE != value))
				{
					this._FLDCONTENTS_DEDUCTIBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLDCONTENTS_COINSURANCE", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FLDCONTENTS_COINSURANCE
		{
			get
			{
				return this._FLDCONTENTS_COINSURANCE;
			}
			set
			{
				if ((this._FLDCONTENTS_COINSURANCE != value))
				{
					this._FLDCONTENTS_COINSURANCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLDCONTENTSREPLACEMENTVALUE", DbType="VarChar(20)")]
		public string FLDCONTENTSREPLACEMENTVALUE
		{
			get
			{
				return this._FLDCONTENTSREPLACEMENTVALUE;
			}
			set
			{
				if ((this._FLDCONTENTSREPLACEMENTVALUE != value))
				{
					this._FLDCONTENTSREPLACEMENTVALUE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLDCONTENTSREPLACEMENTCOST", DbType="VarChar(5)")]
		public string FLDCONTENTSREPLACEMENTCOST
		{
			get
			{
				return this._FLDCONTENTSREPLACEMENTCOST;
			}
			set
			{
				if ((this._FLDCONTENTSREPLACEMENTCOST != value))
				{
					this._FLDCONTENTSREPLACEMENTCOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NFIP_FLDCONTENTS_ZONE", DbType="VarChar(200)")]
		public string NFIP_FLDCONTENTS_ZONE
		{
			get
			{
				return this._NFIP_FLDCONTENTS_ZONE;
			}
			set
			{
				if ((this._NFIP_FLDCONTENTS_ZONE != value))
				{
					this._NFIP_FLDCONTENTS_ZONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STIC", DbType="VarChar(200)")]
		public string STIC
		{
			get
			{
				return this._STIC;
			}
			set
			{
				if ((this._STIC != value))
				{
					this._STIC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
